credentials:
  usernames:
    admin:
      email: admin@caucaia.ce.gov.br
      name: Administrador
      password: $2b$12$vu/pYhP7ziuabimM0YHtMuC09fnb9t0HNpnV0YUy9tfL1SAt9/ode
      role: admin
    vigilancia:
      email: vigilancia@caucaia.ce.gov.br
      name: Equipe de Vigilância
      password: $2b$12$vu/pYhP7ziuabimM0YHtMuC09fnb9t0HNpnV0YUy9tfL1SAt9/ode
      role: user
    marcela:
      email: marcela@caucaia.ce.gov.br
      name: Marcela
      password: $2b$12$Qk6zRnGfU.EEDVZLJ3re6VCv6qCiSw2hYyTzk1htWEa78RUmD2KT6
      role: user

cookie:
  expiry_days: 1
  key: painel_sifilis_key_2026
  name: painel_sifilis_cookie

preauthorized:
  emails: []
