credentials:
  usernames:
    admin:
      email: admin@caucaia.ce.gov.br
      name: Administrador
      password: $2b$12$F6qp.sFDlGjdjf5p86NCyOtW5v0i0kCnUUcRDqtHhsXkbbBefnwjy
      role: admin
    vigilancia:
      email: vigilancia@caucaia.ce.gov.br
      name: Equipe de Vigilância
      password: $2b$12$F6qp.sFDlGjdjf5p86NCyOtW5v0i0kCnUUcRDqtHhsXkbbBefnwjy
      role: user

cookie:
  expiry_days: 1
  key: painel_sifilis_key_2026
  name: painel_sifilis_cookie

preauthorized:
  emails: []
